-- tbl_code 1분류 초기화
insert into tbl_code (code_unit, code_name, code_val, create_date) values (1, 'mbti', 0, now());
insert into tbl_code (code_unit, code_name, code_val, create_date) values (1, 'category', 0, now());
insert into tbl_code (code_unit, code_name, code_val, create_date) values (1, 'paper', 0, now());
insert into tbl_code (code_unit, code_name, code_val, create_date) values (1, 'questionType', 0, now());
insert into tbl_code (code_unit, code_name, code_val, create_date) values (1, 'questionClass', 0, now());
insert into tbl_code (code_unit, code_name, code_val, create_date) values (1, 'package', 0, now());

-- tbl_code 2분류 초기화
-- mbti
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, 'ESTJ', 1, now() from tbl_code c where c.code_name = 'mbti';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, 'ESTP', 2, now() from tbl_code c where c.code_name = 'mbti';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, 'ESFJ', 3, now() from tbl_code c where c.code_name = 'mbti';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, 'ESFP', 4, now() from tbl_code c where c.code_name = 'mbti';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, 'ENTJ', 5, now() from tbl_code c where c.code_name = 'mbti';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, 'ENTP', 6, now() from tbl_code c where c.code_name = 'mbti';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, 'ENFJ', 7, now() from tbl_code c where c.code_name = 'mbti';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, 'ENFP', 8, now() from tbl_code c where c.code_name = 'mbti';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, 'ISTJ', 9, now() from tbl_code c where c.code_name = 'mbti';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, 'ISTP', 10, now() from tbl_code c where c.code_name = 'mbti';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, 'ISFJ', 11, now() from tbl_code c where c.code_name = 'mbti';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, 'ISFP', 12, now() from tbl_code c where c.code_name = 'mbti';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, 'INTJ', 13, now() from tbl_code c where c.code_name = 'mbti';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, 'INTP', 14, now() from tbl_code c where c.code_name = 'mbti';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, 'INFJ', 15, now() from tbl_code c where c.code_name = 'mbti';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, 'INFP', 16, now() from tbl_code c where c.code_name = 'mbti';
-- category
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, '가족', 1, now() from tbl_code c where c.code_name = 'category';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, '친구', 2, now() from tbl_code c where c.code_name = 'category';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, '연인', 3, now() from tbl_code c where c.code_name = 'category';
-- paper
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, '무료', 1, now() from tbl_code c where c.code_name = 'paper';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, '유료', 2, now() from tbl_code c where c.code_name = 'paper';
-- questionType
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, 'comAll', 1, now() from tbl_code c where c.code_name = 'questionType';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, 'comTarget', 2, now() from tbl_code c where c.code_name = 'questionType';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, 'addTarget', 3, now() from tbl_code c where c.code_name = 'questionType';
-- questionClass
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, 'family', (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = '가족') as code_val, now() from tbl_code c where c.code_name = 'questionClass';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, 'parents', (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = '가족') as code_val, now() from tbl_code c where c.code_name = 'questionClass';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, 'child', (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = '가족') as code_val, now() from tbl_code c where c.code_name = 'questionClass';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, 'friend', (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = '친구') as code_val, now() from tbl_code c where c.code_name = 'questionClass';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, 'couple', (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = '연인') as code_val, now() from tbl_code c where c.code_name = 'questionClass';
-- package
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, '확인', 1, now() from tbl_code c where c.code_name = 'package';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, '미확인', 2, now() from tbl_code c where c.code_name = 'package';

-- tbl_code 3분류 초기화
-- category
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 3, '아빠', 1, now() from tbl_code c where c.code_unit = 2 and c.code_name = '가족';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 3, '엄마', 2, now() from tbl_code c where c.code_unit = 2 and c.code_name = '가족';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 3, '자녀', 3, now() from tbl_code c where c.code_unit = 2 and c.code_name = '가족';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 3, '친구', 1, now() from tbl_code c where c.code_unit = 2 and c.code_name = '친구';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 3, '연인', 1, now() from tbl_code c where c.code_unit = 2 and c.code_name = '연인';

-- 추가 - questionState
insert into tbl_code (code_unit, code_name, code_val, create_date) values (1, 'questionState', 0, now());
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, '오늘의 문제가 출제되었습니다.', 1, now() from tbl_code c where c.code_name = 'questionState';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, '모든 문제가 출제되어 출제 가능한 문제가 없습니다.', 2, now() from tbl_code c where c.code_name = 'questionState';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, '인원수가 채워지지 않아 문제를 출제할 수 없습니다.', 3, now() from tbl_code c where c.code_name = 'questionState';
insert into tbl_code (code_parent_seq, code_unit, code_name, code_val, create_date) select c.code_seq, 2, '문제출제를 기다리는 중입니다.', 4, now() from tbl_code c where c.code_name = 'questionState';


-- test data zip
-- user
insert into tbl_user (code_mbti, create_date, user_birth, user_id, user_img, user_name, user_phone, user_pwd)
    values ( 7, now(), '20000123', 'admin', 'imgfile.jpg', '관리자', '01011111111', 'admin1234');
insert into tbl_user ( code_mbti, create_date, user_birth, user_id, user_img, user_name, user_phone, user_pwd)
    values ( 7, now(), '20000124', 'family1', 'imgfile.jpg', '부모', '01022222222', 'family1');
insert into tbl_user ( code_mbti, create_date, user_birth, user_id, user_img, user_name, user_phone, user_pwd)
    values ( 7, now(), '20000125', 'family2', 'imgfile.jpg', '자식', '01033333333', 'family2');
insert into tbl_user (code_mbti, create_date, user_birth, user_id, user_img, user_name, user_phone, user_pwd)
    values ( 8, now(), '20000126', 'friend1', 'imgfile.jpg', '친구1', '01044444444', 'friend1');
insert into tbl_user (code_mbti, create_date, user_birth, user_id, user_img, user_name, user_phone, user_pwd)
    values ( 8, now(), '20000127', 'friend2', 'imgfile.jpg', '친구2', '01055555555', 'friend2');
insert into tbl_user (code_mbti, create_date, user_birth, user_id, user_img, user_name, user_phone, user_pwd)
    values ( 8, now(), '20000128', 'friend3', 'imgfile.jpg', '친구3', '01066666666', 'friend3');
insert into tbl_user ( code_mbti, create_date, user_birth, user_id, user_img, user_name, user_phone, user_pwd)
    values ( 9, now(), '20000129', 'couple', 'imgfile.jpg', '애인', '01077777777', 'couple');



-- 공통 질문 insert
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'family') AS code_question_class, '여태까지 말하지 못했던 거짓말이 있다면?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'family') AS code_question_class, '가족들을 위해 소원을 빈다면?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'family') AS code_question_class, '가족들에게 원하는 것이 있다면?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'parents') AS code_question_class, '가 어렸을적 가졌던 꿈은?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'parents') AS code_question_class, '가 가장 좋아하는 음식은?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'parents') AS code_question_class, '가 가장 좋아하는 꽃은?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'parents') AS code_question_class, '가 가장 가보고 싶은 여행지는?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'child') AS code_question_class, '이(가) 좋아하는 취미는?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'child') AS code_question_class, '이(가) 가장 잘하는 특기는?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'child') AS code_question_class, '이(가) 좋아하는 색깔은?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'child') AS code_question_class, '이(가) 좋아하는 계절은? ', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'friend') AS code_question_class, '우리가 처음만난 곳은?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'friend') AS code_question_class, '이제야 말할 수 있다!', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'friend') AS code_question_class, '친구들에게 가장 감동 받은 순간은?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'friend') AS code_question_class, '이(가) 가장 좋아하는 음식은?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'friend') AS code_question_class, '이(가) 멤버들 중 가장 잘하는 것이 있다면?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'friend') AS code_question_class, '이(가) 이 그룹에서 외모순위는 몇 위?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'couple') AS code_question_class, '“이 사람이다!”하고 느꼈던 순간은?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'couple') AS code_question_class, '우리가 처음 만난 날은? (‘날짜’ 혹은 ‘~한 날’)', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'couple') AS code_question_class, '우리가 처음 먹은 음식은?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'couple') AS code_question_class, '이(가) 가장 좋아하는 말은?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'couple') AS code_question_class, '이(가) 가장 좋아하는 간식은?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'couple') AS code_question_class, '이(가) 가장 좋아하는 음식은?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';

-- 추가
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'family') AS code_question_class, '지금 이순간 가족들을 떠올리면서 생각나는 말은? (각각에게)', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'family') AS code_question_class, '가족 구성원으로써의 장점을 각각 말해준다면?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'family') AS code_question_class, '내가 힘들때 가장 힘이 되어준 순간은? (각각에게)', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'family') AS code_question_class, '이제야 말할 수 있다! 가족들에게 서운했던 일화가 있다면? (각각에게)', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'family') AS code_question_class, '일주일동안 가족들과 통화하는 시간을 각각 적어보기', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'friend') AS code_question_class, '우리가 물에 빠진다면, 누구먼저 구할 것인가? (순위 매기기)', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'friend') AS code_question_class, '우리가 모두 교도소에 간다면, 무슨 죄를 저질러서 들어갔을 것 같나?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'friend') AS code_question_class, '여기 있는 내 친구들마다 함께 이루고 싶은 버킷리스트가 있다면?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'friend') AS code_question_class, '친구들의 자식 이름을 정해주기(아들, 딸 한 명씩)', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'friend') AS code_question_class, '친구들 각각에게 배운점이 있다면?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'friend') AS code_question_class, '내가 생각하는 친구들의 가장 큰 장점은?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'friend') AS code_question_class, '나는 친구들을 위해 이것까지 줄 수 있다!', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'family') AS code_question_class, '가족들에게 마지막으로 "사랑해","사랑해요"라고 표현한 적은 언제? (각각에게)', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'family') AS code_question_class, '핸드폰을 켜고, 마지막으로 연락한 날짜 적어보기', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'couple') AS code_question_class, '우리가 처음 본 영화는?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'couple') AS code_question_class, '이 사람을 위해 소원을 딱 세 개 빌 수 있다면?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'couple') AS code_question_class, '"우리" 하면 떠오르는 노래는?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'couple') AS code_question_class, '만나면서 가장 크게 웃었던 순간을 떠올리면?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'couple') AS code_question_class, '나는 당신이 ?? 죄를 지어도 이해해줄 수 있어!', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'family') AS code_question_class, '가족들을 전화번호부에 뭐라고 저장해놨는지?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'friend') AS code_question_class, '가장 어울리는 옷 브랜드 말해주기', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'couple') AS code_question_class, '당신은 이럴때 제일 예뻐(or 멋져)!', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'family') AS code_question_class, '다음 생에는 나의 ???으로 태어나줘~(엄마,아들,애완동물 등등)', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'family') AS code_question_class, '내 가족들은 전생에 나와 무슨 관계였을까?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'friend') AS code_question_class, '이제야 말할 수 있다! 친구들에게 서운했던 일화가 있다면? (각각에게)', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'friend') AS code_question_class, '이 친구하면 떠오르는 캐릭터와 그 이유는?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'couple') AS code_question_class, '나의 이런 부분은 이해해줬으면 좋겠어', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'couple') AS code_question_class, '우리가 싸우더라도 이것만은 지켜줘', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'couple') AS code_question_class, '만나면서 가장 감동받았던 한 순간을 꼽자면?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'couple') AS code_question_class, '내가 힘들어할때 이렇게 해줬으면 좋겠다~ 하는 행동이 있다면?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comAll';

insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'parents') AS code_question_class, '가 나온 초등학교 이름은?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'parents') AS code_question_class, '의 어린시절 별명은?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'parents') AS code_question_class, '의 학창시절 특기는?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'parents') AS code_question_class, '가 지금 이순간 가족들에게 가장 듣고싶은 말은?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'parents') AS code_question_class, '의 결혼 전 연애 횟수는?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'parents') AS code_question_class, '가 가족들끼리 간 여행 중 가장 기억에 남는 여행지는?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';

insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'child') AS code_question_class, '이(가) 받았던 생일선물 중 가장 기억에 남은 생일선물은 무엇일까? ', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'child') AS code_question_class, '이(가) 가장 좋아하는 집밥은?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'child') AS code_question_class, '에게 지금 가장 필요한 것은?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'child') AS code_question_class, '이(가) 꼭 가보고 싶은 곳은?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'child') AS code_question_class, '의 가장 친한 친구 이름은?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'child') AS code_question_class, '이(가) 가족들끼리 간 여행 중 가장 기억에 남는 여행지는?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';

insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'friend') AS code_question_class, '이(가) 가장 좋아하는 노래는?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'friend') AS code_question_class, '이(가) 절대 안먹는 음식은?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'friend') AS code_question_class, '이(가) 가장 좋아하는 음식은?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'friend') AS code_question_class, '이(가) 마지막으로 읽은 책은?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'friend') AS code_question_class, '이(가) 좋아하는 영화 장르는?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'friend') AS code_question_class, '이(가) 핸드폰으로 가장 많이 하는 것은?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'friend') AS code_question_class, '이(가) 마지막으로 본 영상은?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';

insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'couple') AS code_question_class, '이(가) 가장 좋아하는 영화는?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'couple') AS code_question_class, '이(가) 절대 안먹는 음식은?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'couple') AS code_question_class, '이(가) 가장 좋아하는 계절은?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'couple') AS code_question_class, '이(가) 최근에 가장 가지고 싶어 했던 것은?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'couple') AS code_question_class, '이(가) 나와 같이 가고 싶은 곳은?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'couple') AS code_question_class, '이(가) 좋아하는 나의 행동은?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';
insert into tbl_com_question (code_question_type, code_question_class, com_question, create_date) select c.code_seq, (select c.code_seq from tbl_code c where c.code_unit = 2 and c.code_name = 'couple') AS code_question_class, '이(가) 하루를 마무리하며 주로 하는 것은?', now() from tbl_code c where c.code_unit = 2 and c.code_name = 'comTarget';








